# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: portphp
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"

  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=portphp
    volumes:
      - './my-project:/app'
    depends_on:
      - mysql